// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"svc-with-grpc-gateway/api/v1"
	"svc-with-grpc-gateway/internal/handler"
	"svc-with-grpc-gateway/internal/repository"
	"svc-with-grpc-gateway/internal/service"
	"svc-with-grpc-gateway/internal/store"
)

// Injectors from wire.go:

func InitializedServer() svcUserV1.UserServiceServer {
	db := store.NewSQLLite()
	iUserRepository := repository.NewUserRepository(db)
	iUserService := service.NewUserService(iUserRepository)
	userServiceServer := handler.NewUserHandler(iUserService)
	return userServiceServer
}

// wire.go:

var userSets = wire.NewSet(repository.NewUserRepository, service.NewUserService, handler.NewUserHandler)
